
services:
  app:
    build:
      context: ./laravel-backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./laravel-backend:/var/www/html
    networks:
      - app-network
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: nginx_docker
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./laravel-backend:/var/www/html
      - ./laravel-backend/storage/api-docs:/var/www/html/storage/api-docs
      - ./react-frontend/dist:/var/www/frontend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: mysql_docker
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
